#!/usr/bin/env bash

# Checking if the correct number of parameters is provided
if [ $# -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Transfering the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip:~/"

echo "File transferred successfully to $username@$server_ip:~/"
