#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Configure Nginx to redirect /redirect_me to another page
echo 'server {
listen 80;
location = /redirect_me {
return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
}' | sudo tee /etc/nginx/sites-available/default

# Restart Nginx (without using systemctl)
service nginx restart
