#!/usr/bin/env bash
# configuration snippet for the custom error page

echo "Hello World!" > /etc/nginx/html/index.html
echo -e "Ceci n'est pas une page\n" > /etc/nginx/html/404.html

# inside custom-error-page.conf
cat <<EOF > /etc/nginx/snippets/custom-error-page.conf
error_page 404 /404.html;
location = /404.html {
    root /var/www/html;
    internal;
}
EOF

cat <<EOF > /etc/nginx/sites-enabled/default
server {

    listen 80;
    listen [::]:80;
    root /etc/nginx/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
}
EOF
