#!/usr/bin/env bash
# shellcheck disable=SC2009
# Create the PID file
echo $$ > /var/run/myscript.pid

# Set up signal handlers
handle_sigterm() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}
handle_sigint() {
    echo "Y U no love me?!"
}
handle_sigquit() {
    echo "Received SIGQUIT. Deleting PID file and terminating."
    rm -f /var/run/myscript.pid
    exit 0
}
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

# Display "To infinity and beyond" indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done
