#!/usr/bin/env bash
# shellcheck disable=SC2009
# Check the number of arguments
if [ $# -ne 1 ]; then
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi

case "$1" in
    start)
        # Start manage_my_process
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        # Stop manage_my_process
        pid=$(cat /var/run/my_process.pid)
        kill "$pid"
        rm -f /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        # Restart manage_my_process
        $0 stop
        $0 start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
