#!/usr/bin/env bash
# shellcheck disable=SC2009
# Get the PID of the 7-highlander process
highlander_pid=$(pgrep -f "7-highlander")

if [ -n "$highlander_pid" ]; then
    echo "Highlander process found with PID $highlander_pid. Terminating..."
    kill "$highlander_pid"
else
    echo "Highlander process not found."
fi
