#!/usr/bin/env bash
#groups visitors by IP and HTTP status code, and displays this data.
log_file="apache-access.log"
awk '{ ip_count[$1][$NF]++ } END { for (ip in ip_count) { for (code in ip_count[ip]) { print ip_count[ip][code], ip, code } } }' "$log_file" \
    | sort -rn
