#!/usr/bin/env bash
#Prints "Best School" 10 times with goodluck and badluck in between
count=1
while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done
