#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes
hours=0
minutes=1
while [ "$hours" -le 12 ]; do
	if [ "$hours" ==  0 ]; then
		echo "Hour: 0"
	fi
    while [ "$minutes" -le 59 ]; do
        echo "$minutes"
        ((minutes++))
    done
    ((hours++))
	if [ "$hours" == 1 ]; then
		echo "Hour: 1"
	fi
    minutes=1
done | head -n 69
