#!/usr/bin/env bash
#fixing error
cat <<EOF> /etc/nginx/sites-available/default
server {
    listen 80;
    server_name _;

    location / {
        return 200 "Hello Holberton";
    }

    # Other configuration settings...
}
